Калькулятор версия 1
AleksanderNisenbaum/calculator pull request #1
Opened 2022-09-20 13:58 UTC by AleksanderNisenbaum

Верстка для калькулятора

2022-09-20 14:02 UTC, topnotch48 requested changes

2022-09-20 14:02 UTC, topnotch48 commented on script.js
> +    // let resultInput = document.getElementById("result");
мертвый код
давай уберем ненужные комментарии

2022-09-20 14:06 UTC, AleksanderNisenbaum commented on script.js
> +    // let resultInput = document.getElementById("result");
Точно. Удалил

2022-09-20 14:20 UTC, topnotch48 requested changes

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +let res = document.getElementById("res");
лучше использовать const вместо let для селекторов элементов

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +let first = 0;
не понятно что имеется в виду
может left operand & right operand?

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +function func(valueButton){
давай использовать декларативные имена фукнций
название func не очень многое нам говорит о том что происходит

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +        let count = secondNumber.split(dot_check).length - 1;
это строка дублирует строку 31
давай избавимся от этого

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +        if(count === 1 && valueButton === '.'){valueButton = '';}
используешь разное форматирование для {} 
постарайся чтобы это было консистентно

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +        resultInput.value = (firstNumber + ' ' + mathAction + ' ' + secondNumber);
это строка дублирует строку 34

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +function funAction(act){
тоже самое что и выше
давай осмысленные имена

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +    if (mathAction === "+"){ total = first + second;}
мне кажется что проблему с точкой ты решил
но по прежнему возможны проблемы с + и остальными операциями
давай попробуем избавиться и от них тоже

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +    resultInput.value = total;
сейчас длина итогового выражения ничем не ограничена
хорошей практикой считается иметь адекватные ограничения
в данном случае я думаю мы не хотели бы чтобы выражение выезжало за границы экрана

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +    first = Number(firstNumber);
как насчет обработки ошибок?

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +sum.onclick = function (){funAction('+')};
было бы здорово иметь по функции на каждое из действий
цифры могут пере-использовать одну и ту же функцию

2022-09-20 14:20 UTC, topnotch48 commented on style.css
> +#div {
давай использовать какую то конвенцию
подобные названия очень быстро станет тяжело различать
https://getbem.com/naming/

2022-09-20 14:20 UTC, topnotch48 commented on index.html
> +    <script src="script.js"></script>
наверно мы могли бы загрузить скрипт асинхронно
в данном случае это ничего не даст
но возможно интересно будет почитать на досуге
https://www.w3schools.com/tags/att_script_async.asp

2022-09-20 14:20 UTC, topnotch48 commented on script.js
> +let res = document.getElementById("res");
как проверить работоспособность данного продукта?
давай попробуем добавить unit testы 
не обязательно в этой версии - но не стоит это откладывать

2022-09-20 18:49 UTC, AleksanderNisenbaum commented on script.js
> +let res = document.getElementById("res");
Не знал. Обязательно уточню этот вопрос.

2022-09-20 18:56 UTC, AleksanderNisenbaum commented on script.js
> +let first = 0;
В коде выше их нет. Может имелось ввиду firstNumber & secondNumber ?

2022-09-20 18:59 UTC, AleksanderNisenbaum commented on script.js
> +function func(valueButton){
Возможно такое имя подойдет summand initializer (инициализатор слагаемых)

2022-09-20 19:01 UTC, AleksanderNisenbaum commented on script.js
> +        let count = secondNumber.split(dot_check).length - 1;
Напишу для этого функцию и применю ее дважды .

2022-09-20 19:03 UTC, AleksanderNisenbaum commented on script.js
> +        if(count === 1 && valueButton === '.'){valueButton = '';}
Не понял в чем суть разного форматирования для скобок в данном случае.

2022-09-20 19:04 UTC, AleksanderNisenbaum commented on script.js
> +    first = Number(firstNumber);
Не понял что имеется ввиду.

2022-09-20 19:08 UTC, AleksanderNisenbaum commented on script.js
> +sum.onclick = function (){funAction('+')};
Имеется ввиду под каждое математическое действие иметь собственную функцию а не как у меня все математические действия в одной функции?

2022-09-20 19:09 UTC, AleksanderNisenbaum commented on style.css
> +#div {
Про нейминг селекторов?(#div)

2022-09-20 19:10 UTC, AleksanderNisenbaum commented on index.html
> +    <script src="script.js"></script>
Наверно вы правы с целью расширения горизонтов.

2022-09-20 19:10 UTC, AleksanderNisenbaum commented on script.js
> +let res = document.getElementById("res");
Хорошая идея.

2022-09-21 09:55 UTC, topnotch48 commented on script.js
> +let res = document.getElementById("res");
ты не будешь их мутировать
если бы был линтер он бы это подсветил
например
https://eslint.org/

2022-09-21 09:56 UTC, topnotch48 commented on script.js
> +let first = 0;
это не всегда числа
как быть с ситуацией когда слева 5 + 2 
это еще не число
оно не подсчитано - для этого есть термин - операнд
тогда (5 + 2) + 3 состоит из 2 операндов 5 + 2 и 3

2022-09-21 09:58 UTC, topnotch48 requested changes

2022-09-21 09:58 UTC, topnotch48 commented on script.js
> +function func(valueButton){
это функция занимается только обработкой . насколько я понял
я бы попробовал переосмыслить весь дизайн вычислений
потому как сейчас не совсем ясно как это тестировать
+ есть баги

2022-09-21 10:04 UTC, topnotch48 commented on script.js
> +        if(count === 1 && valueButton === '.'){valueButton = '';}
else{firstNumber += valueButton} сделано inline
if(mathAction === '') { сделан переносом

было бы круто если бы все было в одном стиле
например
else {
firstNumber += valueButton
}

2022-09-21 10:07 UTC, topnotch48 commented on script.js
> +sum.onclick = function (){funAction('+')};
у тебя сейчас не работают + - / и *
как они обычно это делают в калькуляторе
сейчас некая особенная смесь
не обязательно иметь по функции на оператор
но было бы здорово прикинуть какой интерфейс для работы предоставляет твой модуль
чтобы его можно было бы пере-использовать и в других местах

see [SOLID](https://en.wikipedia.org/wiki/SOLID#:~:text=In%20software%20engineering%2C%20SOLID%20is,engineer%20and%20instructor%20Robert%20C.)

2022-09-21 10:08 UTC, topnotch48 commented on script.js
> +    first = Number(firstNumber);
что если firstNumber нельзя преобразовать в число
что тогда произойдет с программой?

2022-09-21 10:08 UTC, topnotch48 commented on style.css
> +#div {
да нейминг просто хуже не придумаешь

2022-10-10 16:46 UTC, topnotch48 commented
Выглядит и работает намного лучше
но есть проблема с отрицательными числами - я не могу просто ввести отрицательное число например "-5+10"
система просто не позволяет этого сделать

2022-10-10 16:48 UTC, topnotch48 commented
Выглядит так как будто ввод калькулятор ничем не ограничен
я могу ввести сколько угодно длинное число и при этом не буду видеть его конца
мне кажется это не лучший UX
давай попробуем ограничить поле ввода видимой областью?

2022-10-10 17:23 UTC, topnotch48 requested changes

2022-10-10 17:23 UTC, topnotch48 commented on script.js
>  let multiple = document.getElementById("multiple");
Повторюсь - ты не мутируешь эти переменные
почему не использовать const?

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +input0.onclick = function (){createString('0')};
`input0.onclick = function (){createString('0')};`
более лучшим способом написать это будет использование лямбд
`input0.onclick = () => createString('0')`

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    let flag1 = 0;
ужасные названия переменных
что такое флаг1
что такое флаг2
пожалуйста давай называть вещи как то осмысленно

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +function createString(num) {
что имеется в виду под createString? что за строки мы создаем?
почему не modifyExpression?
какие есть альтернативы?

2022-10-10 17:23 UTC, topnotch48 commented on script.js
зачем нужна эта пустая строка?

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    {result.value = result.value
форматирование скобок

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    {result.value = result.value
какой смысл этого выражения?
`result.value = result.value`

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +        (num === '.' || num === '+' || num === '-' || num === '/' || num === 'x'))
я где то уже это видел
избавься от дубликатов

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    if(((result.value[result.value.length - 1] === '+') ||
`result.value.length - 1`
давай не будем повторять это 10 раз
используй переменные чтобы сохранять повторяющиеся значения

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    {result.value = result.value
форматирование скобок
+ какой смысл этого выражения?
`result.value = result.value`

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +function createString(num) {
в целом я не могу понять что и как делает эта функция
названия переменных ничего не говорят
код написан грязно
форматирование и комментарии отсутствует
тестов которые бы помогли мне разобраться как это работает тоже нет :(

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +            (resultValue[i] === '+')||
ты мог бы иметь создать приватную функцию 
isExpression(...) и использовать ее везде вместо того чтобы копипастить

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +            arrSymbols.push(str1);
нет идей что тут происходит...
объясните плз

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    function math(arrSymbols, sign, i){
почему эта функция internal к другой функции?

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +        arrSymbols[i-2] = eval(Number(arrSymbols[i-2]) + sign + Number(arrSymbols[i]))
считается что использование eval достаточно опасно
https://stackoverflow.com/questions/13167403/is-javascript-eval-so-dangerous
можешь переписать не используя его?

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +        arrSymbols.splice(i-1, 2);
почему такие параметры?

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    let j = 0
почему ты где то ставишь ; в конце строки а где то нет?

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    while(j < arrLength){
мне кажется мутировать переменную над которой ты итерируешься в цикле это просто очень плохая идея
код тяжело понять
+ это можно привести к ошибкам которые тяжело будет найти

2022-10-10 17:23 UTC, topnotch48 commented on script.js
> +    while(j < arrLength){
зачем нужны эти 2 участка?
чем они отличаются кроме операций?

2022-10-10 17:56 UTC, topnotch48 commented
ты везде используешь кнопки
```
<div id="container">
    Calculator
    <div id="div">
    <input value="" type="text" id="result">
    <input value="c" type="button" id="del">
    <input value="1" type="button" id="input1">
    <input value="2" type="button" id="input2">
    <input value="3" type="button" id="input3">
    <input value="+" type="button" id="sum">
    <input value="4" type="button" id="input4">
    <input value="5" type="button" id="input5">
    <input value="6" type="button" id="input6">
    <input value="-" type="button" id="minus">
    <input value="7" type="button" id="input7">
    <input value="8" type="button" id="input8">
    <input value="9" type="button" id="input9">
    <input value="x" type="button" id="multiple">
    <input value="/" type="button" id="divide">
    <input value="0" type="button" id="input0">
    <input value="." type="button" id="dot">
    <input value="=" type="button" id="res">
    </div>
</div>
```
Но отображение кнопок зависит от браузера - то есть верстка может поехать или вести себя не одинаково
обычно либо [резетят](https://css-tricks.com/reboot-resets-reasoning/) стили 
либо не используют кнопки а вместо них используют стилизованные div'ы

2022-10-11 12:36 UTC, AleksanderNisenbaum commented on script.js
>  let multiple = document.getElementById("multiple");
Под мутированием подразумевается изменение значения переменной в процессе работы кода?

2022-10-11 13:11 UTC, AleksanderNisenbaum commented on script.js
> +input0.onclick = function (){createString('0')};
Стрелочные функции ))) ок

2022-10-11 15:40 UTC, AleksanderNisenbaum commented on script.js
> +    let flag1 = 0;
Индикаторы начала строки с мат. знака и повторения мат. знаков друг за другом. Согласен что в данном случае имена не передают суть функционала переменных. Исправил.

2022-10-11 15:42 UTC, AleksanderNisenbaum commented on script.js
> +function createString(num) {
Создаю строку символов которые вводит пользователь для математики. Можно наверно и modifyExpression.

2022-10-11 16:30 UTC, AleksanderNisenbaum commented on script.js
Это условие что если длинна result.value равна нулю то есть туда еще ничего не записали . Условие чтобы знаки нельзя было записать вперед цифр. Минус теперь можно.

2022-10-11 16:32 UTC, AleksanderNisenbaum commented on script.js
> +        arrSymbols[i-2] = eval(Number(arrSymbols[i-2]) + sign + Number(arrSymbols[i]))
Надо разобраться. Альтернатив пока не знаю. Это была проблема как мат. знак поместить в переменную чтобы он воспринимался как мат. знак а не просто стока.

2022-10-11 16:36 UTC, AleksanderNisenbaum commented on script.js
> +        arrSymbols.splice(i-1, 2);
? а почему бы и нет

2022-10-11 16:46 UTC, AleksanderNisenbaum commented on script.js
> +        arrSymbols.splice(i-1, 2);
Не понял о чем речь . Возможно почему перемещаюсь по индексам массива?

2022-10-11 16:46 UTC, AleksanderNisenbaum commented on script.js
> +    let j = 0
Описка

2022-10-11 17:56 UTC, topnotch48 commented on script.js
>  let multiple = document.getElementById("multiple");
да

2022-10-11 17:57 UTC, topnotch48 commented on script.js
> +input0.onclick = function (){createString('0')};
arrow functions, да

2022-10-11 17:58 UTC, topnotch48 commented on script.js
> +function createString(num) {
названия функций и переменных должны нести смысловую нагрузку
если названий не достаточно - то пишут комментарии 
чтобы тот кто читает этот код не занимался расшифровкой а мог бы сразу понять что тут происходит
про текущую имплементацию я такого не могу сказать

2022-10-11 17:59 UTC, topnotch48 commented on script.js
на 45 строке просто пустая строка которая разрывае
<img width="880" alt="Screenshot 2022-10-11 at 19 58 53" src="https://user-images.githubusercontent.com/5304470/195165360-e9bdee3b-6469-413b-aa88-2dc1d19085cf.png">
т выражение

2022-10-11 18:00 UTC, topnotch48 commented on script.js
> +        arrSymbols[i-2] = eval(Number(arrSymbols[i-2]) + sign + Number(arrSymbols[i]))
зачем вообще это делать
почему нельзя просто посмотреть знак и на его основе выполнить код написав банальный switch?
```
switch(sign) {
"+": // do sum
"-": // do sub
...
}
```
это максимально просто
максимально быстро
и не позволяет делать injection как eval - то есть еще и безопастно

2022-10-11 18:01 UTC, topnotch48 commented on script.js
> +        arrSymbols.splice(i-1, 2);
функция называется математика
и делает 
`arrSymbols[i-2] = eval(Number(arrSymbols[i-2]) + sign + Number(arrSymbols[i]))
        arrSymbols.splice(i-1, 2);`
        
        что это?
        почему arrSymbols.splice(i-1, 2)

2022-10-11 18:02 UTC, topnotch48 commented on script.js
> +    let j = 0
поставь плз linter что я скинул
в js не нужно ставить ; в конце строк

2022-10-21 18:16 UTC, merged